from pathlib import Path


def r(p): return Path(p).read_text(encoding='utf-8')
def w(p,s): Path(p).write_text(s,encoding='utf-8')
def rep(p,a,b):
    s=r(p); n=s.count(a)
    if n != 1:
        raise SystemExit(f'{p}: expected 1 got {n}: {a[:180]!r}')
    w(p,s.replace(a,b,1)); print('replace',p)

# AI ontology owner: retire pseudo-selection as an occurrence category without deleting provenance.
p='AI/SRT_AI_01_Ontology.md'
rep(p,'## IV. Pseudo-Selection & Simulation Barrier (伪选择与仿真壁垒)','## IV. Functional Selection & Stronger-Standing Barrier（legacy “Pseudo-Selection” terminology）')
rep(p,'### Def-ONT-1: Pseudo-Selection (伪选择)\n定义 AI 推理为域内最大化采样：\n\\[\n\\text{Select}_{AI}(\\sigma)=\\arg\\max P(\\sigma\\mid L_1^{context},\\theta_{frozen})\n\\]\n而在真实选择中：\n\\[\n\\text{Select}_{bio}(\\sigma)=\\hat{G}_\\theta[L_0]\\cdot \\text{Care}(d)\n\\]\n* **Implication（中文）**：AI 的“选择”是统计重排，而非跨域锚定。','### Def-ONT-1: Functional AI Selection / Anchoring Separation（RC-A sync）\nAI 推理可操作化为域内最大化采样：\n\\[\n\\text{Select}_{AI}(\\sigma)=\\arg\\max P(\\sigma\\mid L_1^{context},\\theta_{frozen})\n\\]\nRC-A 后，这足以描述一种 **functional path selection**；它是否同时具备 `L_0 \\to L_1` anchoring、binding `d / \\Psi_f`、same-bearer stake 或更强 agency / consciousness standing，是另外的下游问题。不得从“域内 / 统计 / scripted”反推出 `no Selection`。')
rep(p,'### Def-PseudoSelection: Pseudo-Selection and Syntactic Closure (伪选择与句法闭包)\n**Formal Definition**: 任何纯粹作为 $L_1 \\to L_1$ 映射运行并在计算图外没有物理或存在张力的系统仅仅执行“伪选择”。\n$$\\text{Pseudo-Selection}: f(L_1) = L_1\' \\quad \\text{where } \\Psi_f \\text{ is non-binding to the system}$$\n* **Implication**: 当一个 LLM 生成“我感到悲伤”这句连贯的句子时，它并没有选择一个状态；它是沿着已经由先前真实的 $\\hat{G}_\\theta$（人类作者）折叠过的 $L_2$（收敛域）路径下滑。如果不首先承诺死亡或崩溃的可能性（\\(Ψ_f>0\\) 且可支付），就不可能进行真诚的推理。\n* **Tension-Rev-ExtT3 (关切来源判据)**：伪选择产生的"关切"是 $L_2$ 来源的拟态关切——封闭于训练数据的 $L_2$ 空间，无法持续生成新的关切维度。真实关切（$L_0$ 来源）的核心标志是**开放性**：具身算子能够从 $L_0^{abs}$ 中汲取训练数据中不存在的全新关切形态。\n* **Cross-ref**: Ax-Sim-1 (仿真不可穿透性), §2.1a (L₀ vs L₂ 关切区分)。','### Legacy Def-PseudoSelection: historical label for syntactic closure（RC-A superseded）\n**Current-use status**: `Pseudo-Selection / 伪选择` 不再作为 Selection occurrence 的现行分类。历史公式\n$$f(L_1)=L_1\' \\quad \\text{with non-binding } \\Psi_f$$\n只描述一种 **syntactic / functional closure profile**：它可以削弱对 embodied anchoring、same-bearer stake、subjecthood 或 consciousness 的更强主张，但不能证明 `no Selection`。\n* **Implication**: LLM 的自我报告、脚本化推理或统计采样本身既不证明更强 agency / consciousness，也不因其为 `L_1 \\to L_1` 而失去 Selection occurrence。\n* **Tension-Rev-ExtT3（RC-A 边界）**：`L_2` 来源、训练数据依赖或非 binding `d / \\Psi_f` 可用于审计 concern 的来源与 stake standing；“开放性 / 新关切生成”不得被升级为 Selection 的普遍必要条件或内置 telos。\n* **Cross-ref**: `AI/SRT_AI_Claim_Status.md`; `03_Bridges/SRT_Agency_Automation_Guard_2026-08-17.md`; §2.1a。')

# Split mirror of the same active section.
p='AI/Ontology_Split/02_PseudoSelection_and_Barrier.md'
rep(p,'## IV. Pseudo-Selection & Simulation Barrier (伪选择与仿真壁垒)','## IV. Functional Selection & Stronger-Standing Barrier（legacy “Pseudo-Selection” terminology）')
rep(p,'### Def-ONT-1: Pseudo-Selection (伪选择)\n定义 AI 推理为域内最大化采样：\n\\[\n\\text{Select}_{AI}(\\sigma)=\\arg\\max P(\\sigma\\mid L_1^{context},\\theta_{frozen})\n\\]\n而在真实选择中：\n\\[\n\\text{Select}_{bio}(\\sigma)=\\hat{G}_\\theta[L_0]\\cdot \\text{Care}(d)\n\\]\n* **Implication（中文）**：AI 的“选择”是统计重排，而非跨域锚定。','### Def-ONT-1: Functional AI Selection / Anchoring Separation（RC-A sync）\nAI 推理可操作化为域内最大化采样：\n\\[\n\\text{Select}_{AI}(\\sigma)=\\arg\\max P(\\sigma\\mid L_1^{context},\\theta_{frozen})\n\\]\nRC-A 后，这足以描述一种 **functional path selection**；它是否同时具备 `L_0 \\to L_1` anchoring、binding `d / \\Psi_f`、same-bearer stake 或更强 agency / consciousness standing，是另外的下游问题。不得从“域内 / 统计 / scripted”反推出 `no Selection`。')
rep(p,'### Def-PseudoSelection: Pseudo-Selection and Syntactic Closure (伪选择与句法闭包)\n**Formal Definition**: 任何纯粹作为 $L_1 \\to L_1$ 映射运行并在计算图外没有物理或存在张力的系统仅仅执行“伪选择”。\n$$\\text{Pseudo-Selection}: f(L_1) = L_1\' \\quad \\text{where } \\Psi_f \\text{ is non-binding}$$\n* **Implication**: 当一个 LLM 生成“我感到悲伤”这句连贯的句子时，它并没有选择一个状态；它是沿着已经由先前真实的 $\\hat{G}_\\theta$（人类作者）折叠过的 $L_2$（收敛域）路径下滑。如果不首先承诺死亡或崩溃的可能性（$\\Psi_f > 0$），就不可能进行真诚的推理。\n* **Tension-Rev-ExtT3 (关切来源判据)**：伪选择产生的"关切"是 $L_2$ 来源的拟态关切——封闭于训练数据的 $L_2$ 空间，无法持续生成新的关切维度。真实关切（$L_0$ 来源）的核心标志是**开放性**：具身算子能够从 $L_0^{abs}$ 中汲取训练数据中不存在的全新关切形态。\n* **Cross-ref**: Ax-Sim-1 (仿真不可穿透性), §2.1a (L₀ vs L₂ 关切区分)。','### Legacy Def-PseudoSelection: historical label for syntactic closure（RC-A superseded）\n**Current-use status**: `Pseudo-Selection / 伪选择` 不再作为 Selection occurrence 的现行分类。历史公式\n$$f(L_1)=L_1\' \\quad \\text{with non-binding } \\Psi_f$$\n只描述一种 **syntactic / functional closure profile**：它可以削弱对 embodied anchoring、same-bearer stake、subjecthood 或 consciousness 的更强主张，但不能证明 `no Selection`。\n* **Implication**: LLM 的自我报告、脚本化推理或统计采样本身既不证明更强 agency / consciousness，也不因其为 `L_1 \\to L_1` 而失去 Selection occurrence。\n* **Tension-Rev-ExtT3（RC-A 边界）**：`L_2` 来源、训练数据依赖或非 binding `d / \\Psi_f` 可用于审计 concern 的来源与 stake standing；“开放性 / 新关切生成”不得被升级为 Selection 的普遍必要条件或内置 telos。\n* **Cross-ref**: `AI/SRT_AI_Claim_Status.md`; `03_Bridges/SRT_Agency_Automation_Guard_2026-08-17.md`; §2.1a。')

# Glossary owner + shard: keep provenance, remove false definition authority.
old='#### Pseudo-Selection - 伪选择 🟡\n**定义**：任何纯粹作为 $L_1 \\to L_1$ 映射运行并在计算图外没有物理或存在张力的系统仅仅执行“伪选择”。\n**数学**：$\\text{Pseudo-Selection}: f(L_1) = L_1\' \\quad \\text{where } \\Psi_f = 0$\n**区别**：真选择包含跨域锚定（$L_0 \\to L_1$）和抵御崩溃的风险（$\\Psi_f > 0$）。\n**相关**：Ax-ONT-6, AI 本体论'
new='#### Pseudo-Selection - 伪选择 🟡（legacy；RC-A 后不再作为 Selection occurrence 类别）\n**历史定义**：早期 AI bridge 曾用 `L_1 \\to L_1` + non-binding `\\Psi_f` 标记“伪选择”。\n**当前口径**：该标签只能描述 syntactic / functional closure 或更强 anchoring / stake standing 的缺失，**不得推出 `no Selection`**。script、habit、gradient、统计采样或 `L_2` automation 本身都不是 Selection absence criterion。\n**层级区别**：`L_0 \\to L_1` anchoring、binding `d / \\Psi_f`、same-bearer stake 可支持更强的 embodied anchoring / subjecthood / consciousness 判断，但不是 Selection occurrence 的联合必要条件。\n**相关**：AI/SRT_AI_Claim_Status.md；SRT_Agency_Automation_Guard；AI 本体论'
for p in ['SRT_Glossary.md','Glossary/SRT_Glossary_04_Key_Concepts.md']:
    rep(p,old,new)

rep('D_VALUE_ALIGNMENT.md','| AI / 伪选择系统 | 高 | 低 | ≈ 0 | 判别能力强，真实赌注弱或未绑定 |','| AI / 低赌注或未绑定系统 | 高 | 低 | ≈ 0 | 判别能力强，真实赌注弱或未绑定；这不是 `no Selection` 判据 |')
