#!/usr/bin/env python3
"""Audit Markdown frontmatter and authority-layer leakage."""

from __future__ import annotations

import argparse

from governance_common import (
    frontmatter_for,
    iter_markdown,
    print_summary,
    read_text,
    relpath,
    repo_path,
)


RECOMMENDED_KEYS = {
    "id",
    "type",
    "status",
    "layer",
    "epistemic_layer",
    "claim_mode",
}

AUTHORITY_HELPER_MARKERS = (
    "_Split/",
    "_Annex/",
    "/hooks/",
    "/patches/",
    "Operations/",
    "Materials/",
)

BASELINE_FILES = {
    "Governance/Frontmatter_Warning_Baseline.txt",
}


def is_helper_path(rel: str) -> bool:
    return any(marker in rel for marker in AUTHORITY_HELPER_MARKERS)


def load_baseline(path_arg: str) -> set[str]:
    path = repo_path(path_arg)
    if not path.is_file():
        raise FileNotFoundError(path)
    return {
        line.strip()
        for line in read_text(path).splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    }


def write_baseline(path_arg: str, warnings: list[str]) -> None:
    path = repo_path(path_arg)
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Frontmatter warning baseline",
        "#",
        "# One warning per line. Generated by:",
        "# uv run python scripts/check_frontmatter.py --write-baseline Governance/Frontmatter_Warning_Baseline.txt",
        "#",
        "# Existing warnings are treated as known debt by governance_preflight.py.",
        "# Remove lines when the corresponding files are fixed.",
        "",
        *sorted(set(warnings)),
    ]
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--strict", action="store_true")
    parser.add_argument("--include-artifacts", action="store_true")
    parser.add_argument("--baseline", help="Known warning baseline file.")
    parser.add_argument("--write-baseline", help="Write current warnings to this baseline file.")
    parser.add_argument(
        "--fail-on-new-warnings",
        action="store_true",
        help="Exit nonzero when warnings are not present in --baseline.",
    )
    args = parser.parse_args()

    errors: list[str] = []
    warnings: list[str] = []
    ids: dict[str, str] = {}
    baseline_paths = {
        relpath(repo_path(path_arg))
        for path_arg in [args.baseline, args.write_baseline]
        if path_arg
    }
    baseline_paths.update(BASELINE_FILES)

    for path in iter_markdown(include_artifacts=args.include_artifacts):
        rel = relpath(path)
        if rel in baseline_paths:
            continue
        fm = frontmatter_for(path)
        if fm is None:
            message = f"{rel}: missing frontmatter"
            if args.strict:
                errors.append(message)
            else:
                warnings.append(message)
            continue
        if fm.malformed:
            errors.append(f"{rel}: malformed frontmatter fence")
            continue

        missing = sorted(RECOMMENDED_KEYS - set(fm.data))
        if missing:
            message = f"{rel}: missing recommended frontmatter keys: {', '.join(missing)}"
            if args.strict:
                errors.append(message)
            else:
                warnings.append(message)

        file_id = fm.data.get("id")
        if file_id:
            previous = ids.get(file_id)
            if previous and previous != rel:
                warnings.append(f"duplicate frontmatter id `{file_id}`: {previous} / {rel}")
            ids[file_id] = rel

        if is_helper_path(rel):
            claim_mode = fm.data.get("claim_mode", "")
            canonical = fm.data.get("canonical", "")
            if canonical.lower() == "true":
                errors.append(f"{rel}: helper-layer file declares canonical: true")
            if claim_mode == "canonical":
                warnings.append(f"{rel}: helper-layer file uses claim_mode: canonical")

    if args.write_baseline:
        write_baseline(args.write_baseline, warnings)
        print(f"frontmatter_baseline: wrote={args.write_baseline} warnings={len(set(warnings))}")

    display_warnings = warnings
    if args.baseline:
        try:
            baseline = load_baseline(args.baseline)
        except FileNotFoundError as exc:
            errors.append(f"baseline file missing: {exc}")
            baseline = set()
        current = set(warnings)
        new_warnings = sorted(current - baseline)
        retired_warnings = sorted(baseline - current)
        known_count = len(current & baseline)
        print(
            "frontmatter_baseline: "
            f"known={known_count} new={len(new_warnings)} retired={len(retired_warnings)}"
        )
        if args.fail_on_new_warnings:
            errors.extend(f"new frontmatter warning: {item}" for item in new_warnings)
            display_warnings = []
        else:
            display_warnings = new_warnings

    print_summary("frontmatter", errors, display_warnings)
    raise SystemExit(1 if errors else 0)


if __name__ == "__main__":
    main()
