#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "SRT"
OUT = ROOT / "_SRT_EXPLAINABILITY_AUDIT.md"

BLOCKS = {
    "definition": ["定义（Definition）", "Definition"],
    "formalization": ["形式化（Formalization）", "Formalization"],
    "mechanism": ["机制解释（Mechanism）", "Mechanism"],
    "falsification": ["可证伪条件（Falsification）", "Falsification"],
    "boundary": ["## 【理论边界/防误用声明】"],
}


def candidate(text: str, rel: str) -> bool:
    if rel.startswith("_") or rel.endswith("_TEMPLATE.md"):
        return False
    if rel in {"SRT_Glossary.md", "SRT_Navigation_Map.md", "SRT_Quick_Start.md"}:
        return False
    keys = ["Part A", "形式化公理", "Axiom", "Equation", "Hypothesis"]
    return any(k in text for k in keys)


def has_any(text: str, needles):
    return any(n in text for n in needles)


def main():
    files = sorted(ROOT.rglob("*.md"))
    rows = []
    total_ratio = 0.0
    full = 0
    partial = 0

    for p in files:
        rel = p.relative_to(ROOT).as_posix()
        txt = p.read_text(errors="ignore")
        if not candidate(txt, rel):
            continue

        present = {k: has_any(txt, v) for k, v in BLOCKS.items()}
        score = sum(1 for v in present.values() if v)
        ratio = score / len(BLOCKS)
        total_ratio += ratio
        if score == len(BLOCKS):
            full += 1
        elif score >= 2:
            partial += 1

        missing = [k for k, v in present.items() if not v]
        rows.append((rel, score, missing))

    n = len(rows)
    completeness = (total_ratio / n * 100.0) if n else 0.0
    full_ratio = (full / n * 100.0) if n else 0.0
    partial_ratio = (partial / n * 100.0) if n else 0.0

    lines = [
        "---",
        "id: SRT-EXPLAINABILITY-AUDIT",
        "type: framework",
        "tags: [Explainability, Audit, AutoGenerated]",
        "status: rolling_v1",
        "dependency: [_SRT_EXPLANATION_PROTOCOL, _SRT_QUALITY_SCORECARD]",
        "---",
        "",
        "# SRT Explainability Audit (Auto)",
        "",
        f"- Candidate Docs: {n}",
        f"- Mean Explainability Completeness (5-block ratio): {completeness:.1f}%",
        f"- Full 5/5 Docs: {full}/{n} ({full_ratio:.1f}%)",
        f"- Partial Docs (>=2/5): {partial}/{n} ({partial_ratio:.1f}%)",
        "",
        "## Lowest-score Docs (Top 30)",
        "",
    ]

    rows_sorted = sorted(rows, key=lambda x: x[1])[:30]
    for rel, score, missing in rows_sorted:
        lines.append(f"- `{rel}`: {score}/5, missing={', '.join(missing)}")

    OUT.write_text("\n".join(lines) + "\n")
    print(OUT)


if __name__ == "__main__":
    main()
