#!/usr/bin/env python3
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1] / "SRT"
IGNORE_DIRS = {".venv", ".obsidian", "papers", "node_modules"}

GLOSSARY = ROOT / "SRT_Glossary.md"
CORE_TERMS = ["d-value", "\\Psi_f", "\\hat{G}_\\theta", "L_0 / L_1 / L_2"]


def frontmatter_ok(text: str) -> bool:
    s = text.lstrip("\ufeff")
    return s.startswith("---\n") and "\n---\n" in s[4:]


def compute_boundary_coverage(md_files):
    # 忽略 registry/template/changelog 等工程文件
    excluded = (
        "_SRT_",
        "SRT_Glossary.md",
        "SRT_Navigation_Map.md",
        "SRT_Quick_Start.md",
    )
    candidates = []
    with_boundary = 0
    for p in md_files:
        rel = p.relative_to(ROOT).as_posix()
        if rel.startswith("_") or any(x in rel for x in excluded):
            continue
        if rel.endswith("_TEMPLATE.md"):
            continue
        txt = p.read_text(errors="ignore")
        # 理论文档粗筛：包含 Part A/Part B 或 Axiom/Equation/Hypothesis 关键词
        if not any(k in txt for k in ["Part A", "Axiom", "Equation", "Hypothesis", "形式化公理"]):
            continue
        candidates.append(rel)
        if "## 【理论边界/防误用声明】" in txt:
            with_boundary += 1
    ratio = (with_boundary / len(candidates) * 100.0) if candidates else 0.0
    return len(candidates), with_boundary, ratio


def compute_terminology_coverage():
    if not GLOSSARY.exists():
        return 0, 0, 0.0
    txt = GLOSSARY.read_text(errors="ignore")
    hit = 0
    for term in CORE_TERMS:
        if term in txt:
            hit += 1
    ratio = hit / len(CORE_TERMS) * 100.0
    return len(CORE_TERMS), hit, ratio


def main():
    md_files = sorted(
        p for p in ROOT.rglob("*.md")
        if not any(part in IGNORE_DIRS for part in p.relative_to(ROOT).parts)
    )
    fm_total = len(md_files)
    fm_ok = sum(1 for p in md_files if frontmatter_ok(p.read_text(errors="ignore")))
    fm_ratio = fm_ok / fm_total * 100.0 if fm_total else 0.0

    cand_n, boundary_n, boundary_ratio = compute_boundary_coverage(md_files)
    term_total, term_hit, term_ratio = compute_terminology_coverage()

    report = ROOT / "_SRT_QUALITY_METRICS.md"
    report.write_text(
        "---\n"
        "id: SRT-QUALITY-METRICS-AUTO\n"
        "type: framework\n"
        "tags: [Quality, Metrics, AutoGenerated]\n"
        "status: rolling_v1\n"
        "dependency: [_SRT_QUALITY_SCORECARD]\n"
        "---\n\n"
        "# SRT Quality Metrics (Auto)\n\n"
        f"- Frontmatter Coverage: {fm_ok}/{fm_total} ({fm_ratio:.1f}%)\n"
        f"- Terminology Governance Coverage (core set): {term_hit}/{term_total} ({term_ratio:.1f}%)\n"
        f"- Boundary Header Coverage (theory candidates): {boundary_n}/{cand_n} ({boundary_ratio:.1f}%)\n"
    )
    print(report)


if __name__ == "__main__":
    main()
